In [1]:
import pandas as pd

In [2]:
offers_01 = pd.read_csv('europe_offers_01.csv')
offers_02 = pd.read_csv('europe_offers_02.csv')
offers_03 = pd.read_csv('europe_offers_03.csv')

In [3]:
total_offers = pd.concat([offers_01, offers_02, offers_03], ignore_index=True)
total_offers

,Make,Model,Trim,Year,Mileage(km),kW,Fuel type,Body type,Color,Transmission,Emission standard,Country,City,Price(EUR)
0,Volkswagen,Sharan,2.0 tdi,2013,182000,104.0,Diesel,Van,Gray,Manual,5,Austria,Braunau Am Inn,15499.0
1,Audi,A6,2.7,2009,250000,141.0,Diesel,Sedan,Silver,Manual,5,Austria,Salzburg,8900.0
2,Porsche,Cayenne,3.0 diesel,2011,256000,182.0,Diesel,Suv,Black,Automatic,5,Austria,Braunau Am Inn,25999.0
3,Volkswagen,Passat,2.0 tdi scr,2019,94187,111.0,Diesel,Wagon,Silver,Manual,6,Austria,Wolfsberg,18790.0
4,Volkswagen,Passat,2.0 tdi scr,2019,77167,111.0,Diesel,Wagon,Black,Automatic,6,Austria,Wels,18990.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10245,Volkswagen,Tiguan Allspace,2.0 tdi,2020,58630,141.0,Diesel,Crossover,White,Automatic,6,Sweden,Falun,33194.0
10246,Renault,Clio,1.0 tce,2018,76580,67.0,Petrol,Sedan,Black,Manual,6,Sweden,Östersund,9546.0
10247,Renault,Clio,0.9 tce,2019,30260,56.0,Petrol,Sedan,White,Manual,6,Sweden,Nyköping,10939.0
10248,Porsche,Panamera,4.8,2012,67000,397.0,Petrol,Sedan,White,Automatic,5,Sweden,Kristianstad,61301.0
10249,Hyundai,Tucson,1.6 t-gdi,2017,127000,131.0,Petrol,Suv,Black,Automatic,6,Sweden,Örebro,17070.0

In [4]:
total_offers.to_csv('total_offers.csv', index= False)