In [1]:
import pandas as pd
import numpy as np

In [2]:
offers = pd.read_csv('total_offers.csv')
offers.head()

,Make,Model,Trim,Year,Mileage(km),kW,Fuel type,Body type,Color,Transmission,Emission standard,Country,City,Price(EUR)
0,Volkswagen,Sharan,2.0 tdi,2013,182000,104.0,Diesel,Van,Gray,Manual,5,Austria,Braunau Am Inn,15499.0
1,Audi,A6,2.7,2009,250000,141.0,Diesel,Sedan,Silver,Manual,5,Austria,Salzburg,8900.0
2,Porsche,Cayenne,3.0 diesel,2011,256000,182.0,Diesel,Suv,Black,Automatic,5,Austria,Braunau Am Inn,25999.0
3,Volkswagen,Passat,2.0 tdi scr,2019,94187,111.0,Diesel,Wagon,Silver,Manual,6,Austria,Wolfsberg,18790.0
4,Volkswagen,Passat,2.0 tdi scr,2019,77167,111.0,Diesel,Wagon,Black,Automatic,6,Austria,Wels,18990.0

In [3]:
offers.shape

(10250, 14)

In [4]:
offers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10250 entries, 0 to 10249
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               10250 non-null  object
 1   Model              10250 non-null  object
 2   Trim               10250 non-null  object
 3   Year               10250 non-null  int64
 4   Mileage(km)        10250 non-null  int64
 5   kW                 10250 non-null  float64
 6   Fuel type          10250 non-null  object
 7   Body type          10250 non-null  object
 8   Color              9783 non-null   object
 9   Transmission       10250 non-null  object
 10  Emission standard  10250 non-null  int64
 11  Country            10250 non-null  object
 12  City               9791 non-null   object
 13  Price(EUR)         10250 non-null  float64
dtypes: float64(2), int64(3), object(9)
memory usage: 1.1+ MB

In [5]:

offers.describe()

,Year,Mileage(km),kW,Emission standard,Price(EUR)
count,10250.000000,10250.000000,10250.000000,10250.000000,10250.000000
mean,2017.443902,93971.155122,138.633171,5.734634,27751.626711
std,5.107931,74255.863628,78.497138,0.644271,24855.534833
min,1944.000000,0.000000,9.000000,1.000000,535.000000
25%,2015.000000,32000.000000,89.000000,6.000000,13983.250000
50%,2018.000000,82000.000000,111.000000,6.000000,20997.000000
75%,2021.000000,143000.000000,155.000000,6.000000,33524.500000
max,2024.000000,604000.000000,600.000000,6.000000,609870.000000

In [6]:
# Drop the "City" column as it's not important
offers.drop(columns = ['City'], inplace=True)

Auto ML

In [7]:
!pip install pycaret --user

Requirement already satisfied: pycaret in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (3.3.0)
Requirement already satisfied: ipython>=5.5.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (8.12.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (8.0.4)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (4.65.0)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (1.24.3)
Requirement already satisfied: pandas<2.2.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (1.10.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: scikit-learn>1.4.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (1.4.1.post1)
Requirement already satisfied: pyod>=1.1.3 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (0.12.0)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (2.6.3)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (4.3.0)
Requirement already satisfied: numba>=0.55.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (0.57.0)
Requirement already satisfied: requests>=2.27.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (2.31.0)
Requirement already satisfied: psutil>=5.9.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (5.9.0)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (2.1.1)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (6.0.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (5.7.0)
Requirement already satisfied: cloudpickle in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (2.2.1)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (3.4.1)
Requirement already satisfied: matplotlib<3.8.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (3.7.1)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (5.20.0)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (0.2.1)
Requirement already satisfied: schemdraw==0.15 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (0.9.2)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pycaret) (0.14.0)
Requirement already satisfied: sktime>=0.26.0 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (0.27.0)
Requirement already satisfied: tbats>=1.1.3 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: patsy>=0.5.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from category-encoders>=2.4.0->pycaret) (0.5.3)
Requirement already satisfied: packaging in c:\users\ruoxi\anaconda3\lib\site-packages (from deprecation>=2.1.0->pycaret) (23.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (2.2.0)
Requirement already satisfied: zipp>=0.5 in c:\users\ruoxi\anaconda3\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.11.0)
Requirement already satisfied: backcall in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: stack-data in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (5.7.1)
Requirement already satisfied: colorama in c:\users\ruoxi\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (6.19.2)
Requirement already satisfied: widgetsnbextension~=4.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ruoxi\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.8.2)
Requirement already satisfied: fastjsonschema in c:\users\ruoxi\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\ruoxi\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.17.3)
Requirement already satisfied: jupyter-core in c:\users\ruoxi\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.3.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\ruoxi\anaconda3\lib\site-packages (from numba>=0.55.0->pycaret) (0.40.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pandas<2.2.0->pycaret) (2022.7)
Requirement already satisfied: tzdata>=2022.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from plotly>=5.14.0->pycaret) (8.2.2)
Requirement already satisfied: dash>=2.9.0 in c:\users\ruoxi\appdata\roaming\python\python311\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.16.1)
Requirement already satisfied: orjson<4.0.0,>=3.8.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.9.15)
Requirement already satisfied: tsdownsample==0.1.2 in c:\users\ruoxi\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\ruoxi\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.0.9)
Requirement already satisfied: urllib3 in c:\users\ruoxi\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (1.26.16)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (68.0.0)
Requirement already satisfied: six in c:\users\ruoxi\anaconda3\lib\site-packages (from pyod>=1.1.3->pycaret) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ruoxi\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ruoxi\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ruoxi\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (2023.7.22)
Requirement already satisfied: scikit-base<0.8.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from sktime>=0.26.0->pycaret) (0.7.5)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.2)
Requirement already satisfied: Werkzeug<3.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (5.0.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (4.10.0)
Requirement already satisfied: retrying in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\ruoxi\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.6)
Requirement already satisfied: comm>=0.1.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.1.2)
Requirement already satisfied: debugpy>=1.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (7.4.9)
Requirement already satisfied: pyzmq>=17 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (23.2.0)
Requirement already satisfied: tornado>=6.1 in c:\users\ruoxi\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.3.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.18.0)
Requirement already satisfied: wcwidth in c:\users\ruoxi\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.5)
Requirement already satisfied: platformdirs>=2.5 in c:\users\ruoxi\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (2.5.2)
Requirement already satisfied: pywin32>=300 in c:\users\ruoxi\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (305.1)
Requirement already satisfied: executing in c:\users\ruoxi\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: asttokens in c:\users\ruoxi\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\ruoxi\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.1)
Requirement already satisfied: click>=8.0 in c:\users\ruoxi\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (8.0.4)
Requirement already satisfied: entrypoints in c:\users\ruoxi\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.4)

In [8]:
!pip show pycaret

Name: pycaret
Version: 3.3.0
Summary: PyCaret - An open source, low-code machine learning library in Python.
Home-page: https://github.com/pycaret/pycaret
Author: Moez Ali
Author-email: moez.ali@queensu.ca
License: MIT
Location: C:\Users\ruoxi\AppData\Roaming\Python\Python311\site-packages
Requires: category-encoders, cloudpickle, deprecation, imbalanced-learn, importlib-metadata, ipython, ipywidgets, jinja2, joblib, kaleido, lightgbm, markupsafe, matplotlib, nbformat, numba, numpy, pandas, plotly, plotly-resampler, pmdarima, psutil, pyod, requests, schemdraw, scikit-learn, scikit-plot, scipy, sktime, statsmodels, tbats, tqdm, xxhash, yellowbrick
Required-by:

In [9]:
from pycaret.regression import *

In [10]:
regression_setup = setup(offers, target = 'Price(EUR)')

In [11]:
best_model = compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

In [12]:
# Create the best model
final_model = create_model(best_model)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [13]:
# Tune the best model
tuned_model = tune_model(final_model)
# Evaluate the tuned model
evaluate_model(tuned_model)

Initiated  . . . . . . . . . . . . . . . . . .                   10:11:57
Status     . . . . . . . . . . . . . . . . . .       Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .  Extreme Gradient Boosting

Fitting 10 folds for each of 10 candidates, totalling 100 fits

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [14]:
predict_model(tuned_model)

,Make,Model,Trim,Year,Mileage(km),kW,Fuel type,Body type,Color,Transmission,Emission standard,Country,Price(EUR),prediction_label
3252,Nissan,Qashqai,1.6,2014,135000,96.0,Diesel,Crossover,White,Automatic,6,Sweden,13871.0,12624.096680
1462,Toyota,C-Hr,1.8,2022,58900,90.0,Petrol,Suv,Silver,Automatic,6,Italy,19900.0,24593.263672
10190,Volvo,Xc70,2.5 t,2005,293000,154.0,Petrol,Crossover,Brown,Automatic,4,Sweden,5684.0,8582.356445
4551,Mercedes Benz,C-Class,300,2020,64537,144.0,Hybrid,Wagon,Black,Automatic,6,Germany,26950.0,28080.634766
1802,Suzuki,Baleno,1.0,2019,105030,82.0,Petrol,Van,Silver,Manual,6,Netherlands,13999.0,13660.186523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9418,Volkswagen,Passat,1.5,2021,27600,150.0,Petrol,Sedan,Gray,Automatic,6,Romania,26999.0,26666.679688
601,Volkswagen,Caddy,1.6 tdi,2011,229135,75.0,Diesel,Pickup,Red,Manual,5,Czech Republic,5943.0,9400.173828
6088,Hyundai,Ioniq,1.6,2020,108303,105.0,Electric,Sedan,White,Automatic,6,Spain,18990.0,17087.519531
5668,Fiat,500c,1.0,2021,27000,52.0,Petrol,Convertible,White,Manual,6,Portugal,16950.0,18371.164062
10051,Ford,Mondeo,1.5,2023,163290,120.0,Diesel,Sedan,Black,Automatic,6,Sweden,7873.0,9661.117188

In [15]:
# Save the final model to a file
save_model(final_model, 'best_model_raw_data')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['Year', 'Mileage(km)', 'kW',
                                              'Emission standard'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['Make', 'Model', 'Trim',
                                              'Fuel type', 'Body type', 'Color',
                                              'Transmission', 'Country'],
                                     transformer=SimpleImputer(strategy='most_frequent')...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=-1,
                               num_parallel_tree=None, random_state=3205, ...))]),
 'best_model_raw_data.pkl')

We can see that the best trained models are Extra Trees Regressor and Extreme Gradient Boosting. In Sklearn, Random search will be used for hyperparameter tuning