In [17]:
import pandas as pd
import re

In [18]:
# List to store rearranged dataframes
rearranged_dfs = []

In [19]:
column_names= ['Make', 'Model', 'Trim', 'Year', 'Mileage(km)', 'kW', 'Fuel type', 'Body type', 'Color', 'Transmission', 'Emission standard', 'Contact', 'Country', 'City', 'Price(EUR)']

In [20]:
as_offers = pd.read_csv('cleaned_Austria_offers.csv')

In [21]:
be_offers = pd.read_csv('cleaned_Belgium_offers.csv')
cr_offers = pd.read_csv('cleaned_Czech_offers.csv')
dm_offers= pd.read_csv('cleaned_Denmark_offers.csv')
fr_offers = pd.read_csv('cleaned_France_offers.csv')
gr_offers= pd.read_csv('cleaned_Germany_offers.csv')
hg_offers = pd.read_csv('cleaned_Hungary_offers.csv')
it_offers = pd.read_csv('cleaned_Italy_offers.csv')
nl_offers= pd.read_csv('cleaned_Netherlands_offers.csv')
nw_offers = pd.read_csv('cleaned_Norway_offers.csv')
pl_offers = pd.read_csv('cleaned_Poland_offers.csv')
pt_offers = pd.read_csv('cleaned_Portugal_offers.csv')
rm_offers = pd.read_csv('cleaned_Romania_offers.csv')
sp_offers = pd.read_csv('cleaned_Spain_offers.csv')
st_offers = pd.read_csv('cleaned_Switzerland_offers.csv')
sd_offers = pd.read_csv('cleaned_Sweden_offers.csv')

In [22]:
# Iterate over each dataframe and rearrange columns
for df in [as_offers, be_offers, cr_offers, dm_offers, fr_offers, gr_offers, hg_offers, it_offers, nl_offers, nw_offers, pl_offers, pt_offers, rm_offers, sp_offers, st_offers, sd_offers]:
    rearranged_df = df[column_names]  # Rearrange columns according to the desired order
    rearranged_dfs.append(rearranged_df)

In [23]:
# Concatenate the rearranged dataframes
concatenated_df = pd.concat(rearranged_dfs, ignore_index=True)

In [24]:
concatenated_df.shape

(3117, 15)

In [25]:
concatenated_df.head()

,Make,Model,Trim,Year,Mileage(km),kW,Fuel type,Body type,Color,Transmission,Emission standard,Contact,Country,City,Price(EUR)
0,Ford,Mustang,5.0,2020,25800,335.0,Petrol,Coupe,Red,Automatic,6,https://www.zweispurig.at/ford-mustang-gebrauc...,Austria,Salzburg,56890.0
1,Alfa Romeo,Tonale,1.3,2024,10,208.0,Hybrid,Crossover,Red,Automatic,6,https://www.zweispurig.at/alfa-romeo-tonale-vo...,Austria,Amstetten,59940.0
2,Audi,Q5,2.0 40 TDI quattro,2023,12600,152.0,Diesel,Suv,Black,Automatic,6,https://www.dasweltauto.at/vehicle/20311634,Austria,Eisenstadt,74900.0
3,Mitsubishi,Pajero,3.2 did,2013,149900,149.0,Diesel,Suv,White,Automatic,5,https://www.zweispurig.at/mitsubishi-pajero-ge...,Austria,Stockerau,24990.0
4,Lexus,Nx,300h,2021,27726,146.0,Petrol,Suv,Black,Automatic,6,https://www.zweispurig.at/lexus-nx-gebrauchtwa...,Austria,Enns,40500.0

In [26]:
concatenated_df.describe()

,Year,Mileage(km),kW,Emission standard,Price(EUR)
count,3117.000000,3117.000000,3117.000000,3117.000000,3117.000000
mean,2017.477382,91575.295156,137.337183,5.726339,27515.304296
std,5.484125,74009.283771,76.691458,0.688613,22678.472261
min,1944.000000,0.000000,9.000000,1.000000,535.000000
25%,2015.000000,29049.000000,89.000000,6.000000,14499.000000
50%,2019.000000,79276.000000,111.000000,6.000000,21970.000000
75%,2021.000000,140000.000000,152.000000,6.000000,33499.000000
max,2024.000000,487000.000000,580.000000,6.000000,365000.000000

In [27]:
# I don't think the "Contact" is useful anymore as the links are all expired.
concatenated_df.drop(columns=['Contact'], inplace=True)

In [28]:
# drop missing values from kW
# Change the missing value in "City" to "NA"
#concatenated_df.dropna(subset=['kW'], inplace=True)
concatenated_df.loc[concatenated_df['City'].isna(), 'City'] = "NA"

In [29]:
concatenated_df.isna().sum()

Make                   0
Model                  0
Trim                   0
Year                   0
Mileage(km)            0
kW                     0
Fuel type              0
Body type              0
Color                190
Transmission           0
Emission standard      0
Country                0
City                   0
Price(EUR)             0
dtype: int64

In [30]:
pd.set_option('display.max_rows', None)

In [31]:
concatenated_df['Make'].unique()

array(['Ford', 'Alfa Romeo', 'Audi', 'Mitsubishi', 'Lexus', 'Opel',
       'Mercedes Benz', 'Land Rover', 'Volkswagen', 'Bmw', 'Porsche',
       'Honda', 'Dacia', 'Hyundai', 'Volvo', 'Škoda', 'Maserati', 'Jeep',
       'Fiat', 'Mazda', 'Peugeot', 'Toyota', 'Seat', 'Nissan', 'Suzuki',
       'Jaguar', 'Renault', 'Citroen', 'Kia', 'Cupra', 'Byd', 'Tesla',
       'Abarth', 'Saic', 'Mclaren', 'Ssangyong', 'Subaru', 'Lancia',
       'Mini', 'Chevrolet', 'Dodge', 'Bentley', 'Saab', 'Ds Automobiles',
       'Alpine', 'Ferrari', 'Hummer', 'Cadillac', 'Lamborghini', 'Isuzu',
       'Seres', 'Alpina', 'Infiniti', 'Chrysler', 'Ineos', 'Smart',
       'Karma', 'Lincoln'], dtype=object)

In [32]:
concatenated_df['Model'].unique()

array(['Mustang', 'Tonale', 'Q5', 'Pajero', 'Nx', 'A5', 'Stelvio',
       'Mokka', 'C-Class', 'Evoque', 'S-Max', 'Sharan', 'Transporter',
       'X5', 'Touran', 'Ecosport', 'Cayenne', 'Passat', 'Giulietta', 'X3',
       'Tt', 'Mondeo', 'Hr-V', 'Lodgy', 'A8', 'Transit Custom', 'I10',
       'Xc40', 'Kodiaq', 'Grecale', 'Renegade', 'I30', 'Z4', 'A4 Allroad',
       'Focus', '3 Series', 'Tucson', 'Tipo', 'Glc-Class', '6', 'E-Class',
       'Compass', 'Q7', '508', 'A3', 'Discovery', 'Corolla',
       'Grandland X', 'Gle-Class', 'X1', 'Alhambra', 'Micra', 'Rapid',
       'Vitara', 'Cx-30', '5008', 'Amg Gt', 'Arona', 'Leon', 'A4',
       'Outlander', 'A6', 'Tiguan', 'X-Trail', 'Macan', 'Kona', 'Talento',
       'I-Pace', 'F-Type', 'Trafic', 'C4 Cactus', 'Golf', 'Espace',
       'C-Hr', 'Octavia', 'C4 Spacetourer', 'Ateca', 'Karoq', 'Cls-Class',
       'Touareg', 'Q3', '2008', '5 Series', 'Stinger', 'Sportage', 'Cj5',
       'Range Rover', 'Tarraco', 'Galaxy', '3', '2', 'Cx-60', 'Atto 3',
       'Megane', 'Vito', 'Caddy', 'Fabia', 'V90', 'Superb', '500c',
       'Ranger', 'S60', 'Grand Cherokee', 'Cc', 'Scala', 'Q8', 'Rav4',
       'X4', 'Panamera', 'A1', 'Kuga', 'Eqe', 'Defender', 'Formentor',
       'Xc60', 'Rs4', 'Cx-5', 'Qashqai', 'X7', '911', 'E-Pace', 'Model X',
       'Rsq8', '595', 'Zafira', 'Rs6', 'Q2', 'Marvel R', 'Taycan', 'Eqc',
       'Gt', 'F-Pace', 'S3', 'T-Roc', 'Astra', 'Range Rover Sport',
       'Discovery Sport', 'C4 Picasso', 'Kadjar', 'Korando', 'Insignia',
       'Mustang Mach-E', '208', 'V60', '8 Series', 'S90', 'Corsa', '308',
       'Rcz', 'Polo', 'Sq7', 'Boxster', 'Sl-Class', 'I8', '3008',
       'Gls-Class', 'Forester', 'Ix35', 'Model S', 'Gla-Class', 'Outback',
       '1 Series', 'A6 Allroad', 'Delta', 'Cl-Class', 'Optima', 'Altea',
       'Verso', 'Rc-F', 'Civic', 'Meriva', 'Roomster', 'Xc90', 'Cooper',
       'Sorento', 'S-Class', 'Freemont', 'C4', 'Colorado', 'S80',
       'Challenger', 'X6', 'Tiguan Allspace', 'Santa Fe', 'A7',
       'Grand Vitara', 'Cx-3', 'Fiesta', '7 Series', 'Clubman', 'V50',
       'Auris', 'Fluence', 'Yeti', 'C3', 'Continental Gt', 'C3 Aircross',
       '4 Series', 'I20', 'Up!', 'Crossland X', 'Picanto', '205', 'Xceed',
       'Aygo', 'Vivaro', 'Grand Scenic', 'Citigo', 'Expert', 'C-Max',
       'Ducato', 'Eqb', 'Captur', 'S-Cross', 'Model 3', 'V70', 'C70',
       'Corvette', '911 Turbo', 'Mg Tf', 'Space Star', '9-3', 'C1',
       'Twingo', 'Duster', 'Torino', 'B-Max', 'Rio', '6 Series',
       'Continental Gtc', 'Eos', 'Colt', 'Sx4', 'Stonic', 'Ix3', 'Niro',
       'Grand C-Max', 'Sq5', '500', '928', 'Biturbo', 'Slk-Class',
       'Yaris', 'A-Class', 'Cherokee', 'T-Cross', 'Rx', 'C3 Picasso',
       'Cr-V', 'Spacetourer', 'Juke', 'Ibiza', 'Scenic', 'Ds 7 Crossback',
       'A110', 'Mg5', 'Taigo', 'Clio', 'Ioniq', 'Rs3', 'Kamiq', 'S8',
       'F355', 'Jazz', 'Sandero', 'Sx4 S-Cross', '600e', 'Arteon',
       'F8 Spider', 'Xe', 'Clc-Class', 'S4', 'Xk', 'R8', 'Eqs',
       'Tourneo Custom', 'Model Y', '500 X', 'Sq2', 'Panda', 'Enyaq',
       'M6', 'Berlingo', 'I40', 'Edge', 'Jumper', 'C5 Aircross', 'Soul',
       '300', 'Giulia', 'Torres', 'Transit', 'Eqs Suv', 'Trax', 'H2',
       'Levante', 'Sedici', 'Thesis', 'Puma', 'M4', '500l',
       'Range Rover Velar', 'Navara', 'Ats', 'Mito', 'Ghibli', 'Ml-Class',
       'Hilux', 'Traveller', 'One', 'G-Class', 'Leaf', 'Note', 'E-2008',
       'Swift', 'Grandis', 'Baleno', 'Jetta', 'Ceed', 'Ds 4 Crossback',
       'Xc70', '207', 'Ds3', '2 Series', 'Ux', 'Pathfinder',
       'Flying Spur', 'F Series', 'S7', 'Asx', 'R-Class', 'M5',
       'Land Cruiser V8', 'Gallardo', 'X4m', 'Avensis', 'Camaro',
       'Granturismo', 'Aventador', 'Prius', 'V40 Cross Country', 'D-Max',
       '4008', 'Sf5', 'Is', 'Wrangler', 'Excursion', 'Ev6', 'B7', 'V40',
       'Amarok', 'I3', 'Nv', 'Accord', 'Aveo', 'Talisman', 'B-Class',
       'Cx-7', 'Veloster', 'Clk-Class', 'L200', 'Ds5', 'Gl-Class',
       'C4 Grand Picasso', 'Koleos', 'C5', 'Q50', '200', 'Antara', 'Xf',
       '5', 'Beetle', 'Countryman', 'Venga', '206 Cc', 'Sandero Stepway',
       'Legacy', 'Doblo', 'X-Type', 'Lancer', '159', 'Xsara Picasso',
       'Rexton', 'Cube', 'Zoe', 'Maverick', 'Bravo', 'Proace', 'Jumpy',
       'Kangoo', 'Partner', 'Boxer', 'Logan Mcv', 'V60 Cross Country',
       'M8', 'M3', 'Accent', 'Grenadier', 'Forfour', 'X2', 'Laguna', 'Xj',
       'Combo', 'Bayon', 'Adam', 'Master', 'Bentayga', 'Passat Alltrack',
       'S5', 'Gs', 'S40', 'Sq8', 'Rsq3', 'Rs7', '180', 'Murano', 'Velar',
       'Orlando', 'Impreza', 'Carens', 'Cruze', 'Revero', 'Charger',
       'Scirocco', 'E-Tron', 'Navigator', 'C30'], dtype=object)

In [33]:
#  convert to lowercase
concatenated_df['Trim'] = concatenated_df['Trim'].str.lower()

In [34]:
concatenated_df['Trim'].value_counts()

Trim
2.0                                    287
1.6                                    168
1.2                                    137
1.0                                     99
1.0 tsi                                 92
1.2 puretech                            89
1.5                                     76
2.0 tdi                                 75
1.4                                     62
3.0                                     43
1.8                                     43
1.5 tsi                                 43
1.5 bluehdi                             42
1.6 tdi                                 39
1.3                                     37
1.0 ecoboost                            34
1.5 dci                                 33
electro                                 32
2.5                                     31
1.6 gdi                                 25
1.0 t-gdi                               24
xdrive20d                               23
2.0 tdci                                22
1.2 tce                                 22
1.4 tsi                                 22
1.1                                     20
xdrive30d                               19
450h                                    19
3.0 tdi                                 18
1.0 dig-t                               17
2.4                                     17
2.8                                     16
1.6 t-gdi                               15
1.7 crdi                                13
1.5 35 tfsi                             13
2.0 tdi 4motion                         12
1.0 30 tfsi                             12
2.0 d                                   11
2.0 tsi                                 11
3.0 diesel                              11
1.2 vti                                 11
2.0 ecoblue                             11
1.6 hdi                                 11
2.2                                     11
2.0 tsi vz                              11
1.0 tce                                 11
2.0 35 tdi                              11
1.3 dig-t                               10
sdrive18d                               10
1.6 multijet                            10
d                                       10
2.0 hdi                                 10
0.0 performance                         10
1.6 crdi                                10
5.0                                     10
320d                                     9
300                                      9
2.0 tdi quattro                          9
200                                      9
1.0 25 tfsi                              9
2.4 d5                                   9
520d                                     9
4.0                                      9
2.2 d                                    9
1.2 tsi                                  8
2.0 t8                                   8
1.7 dci                                  8
2.0 40 tdi                               8
250                                      7
3.0 tdi quattro                          7
55 amg                                   7
3.0 d                                    7
350 cdi                                  7
1.6 s                                    7
3.0 crd                                  7
63 amg                                   7
3.0 tdi v6                               7
1.6 dci                                  7
250 4matic                               7
30d                                      7
2.2 hdi                                  7
m40d                                     7
1.0 s tfsi                               7
1.7                                      6
220 d                                    6
350                                      6
2.9                                      6
2.0 tfsi                                 6
1.6 d                                    6
1.9                                      6
1.5 ecoboost                             6
3.0 sdv6                                 6
180                                      6
2.2 cd                                   6
xdrive18d                                6
3.0 tdv6                                 6
1.6 bluehdi                              6
2.0 dci                                  6
318d                                     6
acenta                                   6
2.0 d3                                   6
400                                      6
2.0 tdi ultra                            6
3.6                                      6
1.0 dsg tsi                              5
4.4                                      5
1.6 thp                                  5
2.0 45 tfsi                              5
2.4 d4 awd                               5
3.0 tfsi                                 5
2.2 crdi                                 5
2.0 bluehdi                              5
xdrive40d                                5
2.0 t8 awd                               5
2.5 t5                                   5
1.0 sce                                  5
1.3 tce                                  5
2.0 cdti                                 5
1.2 turbo                                5
3.0 50 tdi                               5
2.0 crdi                                 5
3.0 50 tdi quattro                       5
220 cdi                                  5
200 d                                    5
1.5 etsi                                 5
300h                                     5
500                                      4
1.6 vvt-i                                4
6.0 w12                                  4
320i                                     4
1.8 vvt-i                                4
1.6 puretech                             4
2.0 rs tdi                               4
1.9 tdi                                  4
0.0 long range                           4
3.0 v6                                   4
m850i xdrive                             4
tekna                                    4
1.8 tfsi                                 4
530e                                     4
40d                                      4
0.9 twinair                              4
1.0 limited                              4
2.0 r                                    4
2.3                                      4
1.7 cdti                                 4
2.0 gti                                  4
2.0 30 tdi                               4
4s                                       4
43 amg                                   4
20d                                      4
3.0 s                                    4
4.0 tdi                                  4
1.0 fr tsi                               4
1.0 tfsi                                 4
2.7                                      4
4.4 sdv8                                 3
2.0 40 tdi quattro s tronic              3
1.5 one d                                3
1.6 vti                                  3
2.0 d4 awd                               3
1.0 turbo                                3
740d                                     3
2.9 4 e-hybrid                           3
xdrive40i                                3
530d                                     3
2.4 d4                                   3
1.6 hybrid                               3
180d                                     3
3.6 turbo                                3
electric                                 3
2.0 t5                                   3
750i                                     3
0.9 tce                                  3
1.8 hybrid                               3
1.5 tdci                                 3
2.8 vr6                                  3
730d                                     3
sdrive18i                                3
220d 4matic                              3
1.2 s tfsi                               3
500 4matic                               3
2.0 recharge t8                          3
30d xdrive                               3
1.4 turbo                                3
4.0 amg 55                               3
1.4 tfsi                                 3
2.4 d5 awd                               3
1.4 tdi                                  3
1.0 st                                   3
2.0 t4                                   3
0.9                                      3
m50d                                     3
2.0 mjet                                 3
2.5 turbo                                3
2.0 skyactiv                             3
2.0 35 tdi s tronic                      3
220                                      3
2.8 fsi                                  3
25e xdrive                               2
2.0 40 tdi quattro                       2
6.2                                      2
gt 77 kwh                                2
2.0 t                                    2
1.5 i-vtec                               2
3.5                                      2
2.3 did                                  2
3.2 awd                                  2
40 kwh                                   2
1.0 etsi                                 2
3.4                                      2
118i                                     2
xdrive23d                                2
300 4matic                               2
2.0 sdrive20i                            2
1.4 d-4d                                 2
2.8 crd                                  2
i                                        2
3.0 45 tdi quattro                       2
1.5 ecoblue                              2
2.0 320                                  2
350d 4matic                              2
300e                                     2
330i                                     2
2.0 45 tfsi quattro                      2
3.0 tdi quattro tiptronic                2
1.4 vti                                  2
2.7 tdi                                  2
530d xdrive                              2
2.0 tfsi quattro                         2
2.0 d3 awd                               2
1.0 tsi dsg                              2
2.0 tdi scr                              2
250 cdi be                               2
1.6 cdti                                 2
2.5 tsi                                  2
2.2 tdci                                 2
2.0 tdi bluemotion                       2
2.0 4x4 tdi                              2
220d                                     2
2.0 tsi 4motion                          2
520d xdrive                              2
3.0 320                                  2
1.5 hdi                                  2
1.6 tce                                  2
1.2 tfsi                                 2
2.0 tdi 4drive                           2
1.5 act dsg tsi                          2
3.2                                      2
sdrive16d                                2
2.0 dsg tdi                              2
18d                                      2
2.0 2.0 4x4 tdi                          2
535i                                     2
2.0 p300                                 2
4.0 v8                                   2
6.0                                      2
2.0 hybrid                               2
2.0 tsi cupra                            2
525d                                     2
4.2 fsi                                  2
2.0 t5 awd                               2
325d                                     2
2.1                                      2
3.3                                      2
1.6 tdci                                 2
18i sdrive                               2
5.7                                      2
4.0 tfsi quattro tiptronic               2
320d xdrive                              2
3.3 t-gdi                                2
4.0 tfsi v8                              2
2.5 tfsi                                 2
ev400s                                   2
420d                                     2
525i                                     2
2.0 d-4d                                 2
40i                                      2
turbo                                    2
2.0 40 tfsi                              2
2.0 t8 twin-engine                       2
740d xdrive                              2
5.2 lp 560-4                             1
4.5                                      1
2.0 d5                                   1
1.3 multijet                             1
1.2 i                                    1
218i                                     1
550                                      1
2.0 t3                                   1
2.0 2.0 4x4 dsg tdi                      1
2.5 dci                                  1
640i                                     1
65 amg                                   1
400 cdi                                  1
1.2 mpi                                  1
1.2 tdi                                  1
2.0 xcellence tdi 4drive                 1
4.6 gt                                   1
2.1 d                                    1
1.8 tsi                                  1
2.8 cupra                                1
1.8 t                                    1
xdrive40e                                1
1.5 crdi                                 1
2.0 recharge t6                          1
2.5 d5                                   1
1.0 fr                                   1
4.0 tfsi                                 1
2.0 tfsi s tronic                        1
1.4 tsi act                              1
1.6 diesel                               1
3.0 dct                                  1
xdrive20i                                1
20i xdrive                               1
1.6 ecoboost                             1
3.5 v6                                   1
330e                                     1
xdrive50i                                1
20d xdrive                               1
3.0 m50d                                 1
1.0 ecoboost st                          1
1.2 sport tsi                            1
1.3 gse t4                               1
2.0 titanium                             1
1.0 titanium                             1
1.6 drive                                1
1.0 shine                                1
2.2 i4                                   1
528i                                     1
2.7 d                                    1
230 k                                    1
525d xdrive                              1
160                                      1
2.0 35 tdi quattro                       1
2.0 tdi quattro dpf                      1
350d                                     1
1.4 crdi                                 1
150                                      1
1.9 jts                                  1
1.4 lt                                   1
1.5 s                                    1
2.5 xt                                   1
1.6 limited                              1
1.6 jtdm                                 1
5.0 gt                                   1
3.0 cs                                   1
m50i                                     1
116d                                     1
118d                                     1
1.9 d                                    1
ze 50                                    1
ev320                                    1
2.0 fsi                                  1
5.7 v8                                   1
1.2 jtd                                  1
250d 4matic                              1
1.8 skyactiv-d                           1
4.8 turbo                                1
450                                      1
240                                      1
2.0 duratorq                             1
0.6                                      1
200d                                     1
330i xdrive                              1
325i                                     1
5.0 v10                                  1
2.0 e-boxer                              1
750li xdrive                             1
4.7                                      1
200 cdi                                  1
6.2 zl1                                  1
3.0 tfsi v6                              1
4.8 4s                                   1
6.5 lp 700-4                             1
2.4 d3                                   1
ev400hse                                 1
400 4matic                               1
5.6                                      1
3.0 45 tdi                               1
1.6 one                                  1
sdrive20i                                1
435d xdrive                              1
53 amg 4matic                            1
6.8 v10                                  1
2.0 tdi s-tronic                         1
2.0 t6 awd                               1
2.2 d-4d                                 1
500 sl                                   1
4.8                                      1
2.0 40 tfsi quattro                      1
55 quattro                               1
1.4 t-gdi                                1
1.5 t5 recharge                          1
n-connecta                               1
1.6 e-hdi                                1
640i steptronic                          1
135i                                     1
5.8                                      1
1.0 e                                    1
600                                      1
2.4 v6 multitronic                       1
1.6 mpi                                  1
2.3 jtd                                  1
6.4                                      1
4.0 v8 s                                 1
350 4matic                               1
1.5 dsg tsi                              1
1.0 tdi                                  1
1.9 ddis                                 1
2.0 4x4 dsg tsi                          1
3.8 4s                                   1
1.4 xcellence tsi                        1
1.5 czt                                  1
250d                                     1
2.0 dsg tdi tsi                          1
1.5 i                                    1
350h                                     1
2.9 turbo                                1
2.1 250                                  1
5.4                                      1
320d efficientdynamics                   1
0.0 70 70d 75d 85 ludicrous p90d         1
1.5 t5 twin engine                       1
2.0 d4                                   1
0.0 long performance range standard      1
2.0 cooper d                             1
4.2 v8 quattro                           1
200 cdi be                               1
ev                                       1
m sport                                  1
m50i xdrive                              1
3.0 t6                                   1
1.6 hybrid gdi                           1
43 amg 4matic                            1
3.1                                      1
2.9 gts                                  1
2.0 4x4 scr tdi                          1
xdrive35d                                1
1.6 multijet l2h1                        1
3.0 s diesel                             1
63 amg 4matic+                           1
2.0 30 tdi s tronic                      1
2.5 crdi                                 1
3.0 53                                   1
200 cgi be                               1
316d                                     1
2.0 gt                                   1
2.0 4x4 dsg tdi                          1
1.5 vtec turbo                           1
3.2 did                                  1
0.0 kwh                                  1
114 cdi                                  1
1.6 30 tdi                               1
2.0 fr                                   1
2.2 crd                                  1
m550d                                    1
125i                                     1
4.0 tdi v8                               1
450 amg 4matic                           1
580 4matic                               1
830ci                                    1
gt                                       1
2.0 .35 tdi                              1
1.4 d                                    1

In [35]:
concatenated_df.head(20)

,Make,Model,Trim,Year,Mileage(km),kW,Fuel type,Body type,Color,Transmission,Emission standard,Country,City,Price(EUR)
0,Ford,Mustang,5.0,2020,25800,335.0,Petrol,Coupe,Red,Automatic,6,Austria,Salzburg,56890.0
1,Alfa Romeo,Tonale,1.3,2024,10,208.0,Hybrid,Crossover,Red,Automatic,6,Austria,Amstetten,59940.0
2,Audi,Q5,2.0 40 tdi quattro,2023,12600,152.0,Diesel,Suv,Black,Automatic,6,Austria,Eisenstadt,74900.0
3,Mitsubishi,Pajero,3.2 did,2013,149900,149.0,Diesel,Suv,White,Automatic,5,Austria,Stockerau,24990.0
4,Lexus,Nx,300h,2021,27726,146.0,Petrol,Suv,Black,Automatic,6,Austria,Enns,40500.0
5,Audi,A5,2.0 tfsi,2010,83000,134.0,Petrol,Convertible,Black,Automatic,5,Austria,Leoben,17900.0
6,Alfa Romeo,Stelvio,2.0,2017,105323,155.0,Diesel,Crossover,Gray,Automatic,6,Austria,Amstetten,28940.0
7,Opel,Mokka,1.7,2015,77000,97.0,Diesel,Crossover,White,Manual,6,Austria,Braunau Am Inn,12499.0
8,Mercedes Benz,C-Class,180,2021,76910,90.0,Diesel,Wagon,Red,Automatic,6,Austria,Eisenstadt,29900.0
9,Land Rover,Evoque,2.0,2017,102900,134.0,Diesel,Suv,Gray,Automatic,6,Austria,Graz,27590.0
10,Ford,S-Max,2.0 ecoblue,2020,108200,111.0,Diesel,Mpv,White,Manual,6,Austria,Telfs,24987.0
11,Volkswagen,Sharan,2.0 tdi,2013,182000,104.0,Diesel,Van,Gray,Manual,5,Austria,Braunau Am Inn,15499.0
12,Volkswagen,Transporter,2.0,2023,56067,152.0,Diesel,Van,Black,Automatic,6,Austria,Graz,83900.0
13,Bmw,X5,xdrive30d,2022,99800,213.0,Diesel,Suv,Black,Automatic,6,Austria,Leoben,65990.0
14,Volkswagen,Touran,1.5 tsi,2018,88713,111.0,Petrol,Mpv,Gray,Automatic,6,Austria,Steyr,24490.0
15,Ford,Ecosport,1.0,2020,29975,93.0,Petrol,Suv,White,Manual,6,Austria,Hollabrunn,16990.0
16,Porsche,Cayenne,3.0 diesel,2011,256000,182.0,Diesel,Suv,Black,Automatic,5,Austria,Braunau Am Inn,25999.0
17,Volkswagen,Passat,2.0 tdi scr,2019,77167,111.0,Diesel,Wagon,Black,Automatic,6,Austria,Wels,18990.0
18,Alfa Romeo,Giulietta,1.4,2012,166300,126.0,Petrol,Sedan,Red,Automatic,5,Austria,Linz,7990.0
19,Bmw,X3,d,2005,179000,162.0,Diesel,Suv,Silver,Automatic,4,Austria,Linz,9900.0

In [36]:
concatenated_df.to_csv('europe_offers_02.csv', index= False)